export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const UPDATE_INGREDIENTS = "UPDATE_INGREDIENTS";

export const UPDATE_TOTAL_PRICE = "UPDATE_TOTAL_PRICE";

export const GET_ORDERS = "GET_ORDER";
export const UPDATE_ORDERS = "UPDATE_ORDERS";
